version: "3"

env:
  PROCS:
    sh: nproc
  GOSUMDB: "off"
  GOPROXY: direct
  GOMAXPROCS: 1

tasks:
  runall:
    desc: Run a command in all packages
    cmds:
      - find . -mindepth 2 -name 'go.mod' -print0 | xargs -0 -n1 -P ${PROCS} -- /bin/bash -c 'echo $1; pushd `dirname $1`; {{.CLI_ARGS}}; popd >/dev/null' '_'

  run:
    desc: Run a command in a directory
    cmds:
      - pushd {{index (splitArgs .CLI_ARGS) 0}}; {{index (splitArgs .CLI_ARGS) 1}}; popd >/dev/null
    vars:
      DIRECTORY: splitArgs

  ###########################
  # Runall helpers
  ###########################
  mod-tidy:
    desc: Run "go mod tidy -go=1.21.5" in all packages
    cmds:
      - task: runall
        vars:
          CLI_ARGS: go mod tidy -go=1.21.5
  fmt:
    desc: Run "go fmt" in all packages
    cmds:
      - task: runall
        vars:
          CLI_ARGS: go fmt

  update:
    desc: Run "go get -u ./..." in all packages
    cmds:
      - task: runall
        vars:
          CLI_ARGS: go get -u ./...

  bench:
    desc: Run "go test ./... -v -benchmem -bench=." in all packages
    cmds:
      - task: runall
        vars:
          PROCS: 1
          CLI_ARGS: go test ./... -v -bench=.

  ###########################
  # Others
  ###########################
  test:
    desc: Run "./scripts/test.sh test all"
    cmds:
      - ./scripts/test.sh test all

  test.sh:
    desc: "Run test.sh with the given arguments: go-task test.sh -- test codecs/form"
    cmds:
      - ./scripts/test.sh {{.CLI_ARGS}}
    env:
      ORB_NODOWNLOAD: 1
