version: "3"

env:
  PROCS:
    sh: nproc
  GOSUMDB: "off"
  GOPROXY: direct
  GOMAXPROCS: 1

tasks:
  runall:
    desc: Run a command in all packages
    cmds:
      - find . -mindepth 2 -name 'go.mod' -print0 | xargs -0 -n1 -P ${PROCS} -- /bin/bash -c 'pushd `dirname $1`; {{.CLI_ARGS}}; popd >/dev/null' '_'

  run:
    desc: Run a command in a directory
    cmds:
      - pushd {{index (splitArgs .CLI_ARGS) 0}}; {{index (splitArgs .CLI_ARGS) 1}}; popd >/dev/null
    vars:
      DIRECTORY: splitArgs

  ###########################
  # Runall helpers
  ###########################
  mod-tidy:
    desc: Run "go mod tidy -go=1.21.4" in all packages
    cmds:
      - task: runall
        vars:
          CLI_ARGS: go mod tidy -go=1.21.4
  fmt:
    desc: Run "go fmt" in all packages
    cmds:
      - task: runall
        vars:
          CLI_ARGS: go fmt

  update:
    desc: Run "go get -u ./..." in all packages
    cmds:
      - task: runall
        vars:
          CLI_ARGS: go get -u ./...

  bench:
    desc: Run "go test ./... -v -benchmem -bench=." in all packages
    cmds:
      - task: runall
        vars:
          PROCS: 1
          CLI_ARGS: go test ./... -v -bench=.

  ###########################
  # Others
  ###########################
  mod-replace:
    desc: Replace "github.com/go-orb/* v0.0.0" with the current working directory
    cmds:
      - find . -mindepth 2 -name 'go.mod' -printf "%h\0" | xargs -0 -n1 -P ${PROCS} -- ./scripts/mod-replace.sh
      - task: mod-tidy

  mod-dropreplace:
    desc: Drop all "github.com/go-orb/*" replaces
    cmds:
      - find  . -mindepth 2 -name 'go.mod' -printf "%h\0" | xargs -0 -n1 -P ${PROCS} -- ./scripts/mod-dropreplace.sh
      - task: mod-tidy

  workuse:
    desc: Add go-orb/plugins/* packages to go.work
    cmds:
      - go work use $(find . -mindepth 2 -name 'go.mod' -printf "%h\n")

  test:
    desc: Run "./scripts/test.sh test all"
    cmds:
      - ./scripts/test.sh test all

  test.sh:
    desc: "Run test.sh with the given arguments: go-task test.sh -- test codecs/form"
    cmds:
      - ./scripts/test.sh {{.CLI_ARGS}}
    env:
      ORB_NODOWNLOAD: 1
