name: Unit Tests
on:
  push:
    branches:
      - main
permissions: read-all
jobs:
  golangci:
    name: Lint
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21.5
          check-latest: true
      - name: Run Linters
        run: ./scripts/test.sh lint all
        env:
          PROCS: 1
  test:
    name: Unit Tests
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21.5
          check-latest: true
      - name: Run Unit Tests
        run: ./scripts/test.sh test all
        env:
          PROCS: 1
  summary:
    name: Summary
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21.5
          check-latest: true
      - name: Create Summary
        run: ./scripts/test.sh summary all
        env:
          PROCS: 1
