name: Pull Request
on:
  pull_request: {}
permissions: read-all
jobs:
  lint:
    name: Lint
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Lint files
        uses: go-orb/dagger-for-github
        with:
          version: "v0.14.0"
          verb: call
          args: lint --root=. logs
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
  test:
    name: Unit Tests
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run unit tests
        uses: go-orb/dagger-for-github
        with:
          version: "v0.14.0"
          verb: call
          args: test --root=. logs
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
