name: PR Tests
on:
  pull_request: {}
permissions: read-all
jobs:
  golangci:
    name: Lint
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20"
          check-latest: true
      - name: Run Linters
        run: ./scripts/test.sh lint changes
  test:
    name: Unit Tests
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20"
          check-latest: true
      - name: Run Unit Tests
        run: ./scripts/test.sh test changes
  summary:
    name: Summary
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20"
          check-latest: true
      - name: Create Summary
        run: ./scripts/test.sh summary changes
